# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: web
        
    steps:
    - uses: actions/checkout@v2
      
    - name: Docker Build
      run: docker build -t qr_menu_backend .

    - name: Docker Run
      run: docker run -d -p 9010:5000 --name qr_menu_backend qr_menu_backend
